/*-
 * =================================LICENSE_START==================================
 * toolforge-ngrams-tool
 * ====================================SECTION=====================================
 * Copyright (C) 2022 - 2023 ToolForge
 * ====================================SECTION=====================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ==================================LICENSE_END===================================
 */
package io.toolforge.tool.ngrams;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import java.io.File;
import java.io.FileInputStream;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;
import org.junit.Test;
import com.google.common.io.Resources;
import com.sigpwned.tabular4j.SpreadsheetFactory;
import com.sigpwned.tabular4j.model.TabularWorksheetReader;
import io.toolforge.tool.ngrams.App.NgramCount;
import io.toolforge.toolforge4j.io.InputSource;
import io.toolforge.toolforge4j.io.OutputSink;

public class NgramsTest {
  @Test
  public void smokeTest() {
    List<NgramCount> ngrams = App
        .compute(Stream.of("Hello, world!", "Hello, Dolly!", "Say hello to my little friend!",
            "You had me at hello."), 1, 3)
        .sorted(Comparator.<NgramCount>naturalOrder().reversed()).toList();

    assertThat(ngrams, is(List.of(NgramCount.of("hello", 4), NgramCount.of("had me at", 1),
        NgramCount.of("hello world", 1), NgramCount.of("hello to my", 1),
        NgramCount.of("hello dolly", 1), NgramCount.of("say hello", 1),
        NgramCount.of("to my little", 1), NgramCount.of("world", 1), NgramCount.of("to my", 1),
        NgramCount.of("me at", 1), NgramCount.of("dolly", 1), NgramCount.of("you", 1),
        NgramCount.of("say", 1), NgramCount.of("had", 1), NgramCount.of("to", 1),
        NgramCount.of("my", 1), NgramCount.of("me", 1), NgramCount.of("at", 1),
        NgramCount.of("me at hello", 1), NgramCount.of("hello to", 1),
        NgramCount.of("little friend", 1), NgramCount.of("you had", 1), NgramCount.of("little", 1),
        NgramCount.of("had me", 1), NgramCount.of("friend", 1), NgramCount.of("say hello to", 1),
        NgramCount.of("my little", 1), NgramCount.of("at hello", 1), NgramCount.of("you had me", 1),
        NgramCount.of("my little friend", 1))));
  }

  @Test
  public void spreadsheetTest() throws Exception {
    File ngramsCsv = File.createTempFile("ngrams.", ".csv");
    ngramsCsv.deleteOnExit();

    File ngramsXlsx = File.createTempFile("ngrams.", ".xlsx");
    ngramsXlsx.deleteOnExit();

    Configuration configuration = new Configuration();
    configuration.data = new InputSource(Resources.getResource("mlb_players_2021.csv").toURI());
    configuration.minNgramLength = 1L;
    configuration.maxNgramLength = 1L;
    configuration.textColumnName = "Name";
    configuration.ngramsCsv = new OutputSink(ngramsCsv.toURI());
    configuration.ngramsXlsx = new OutputSink(ngramsXlsx.toURI());

    App.main(configuration);

    String[][] expected = new String[][] {{"ryan", "1", "24"}, {"kyle", "1", "24"},
        {"nick", "1", "22"}, {"jose", "1", "20"}, {"tyler", "1", "19"}, {"luis", "1", "18"},
        {"jake", "1", "18"}, {"matt", "1", "17"}, {"josh", "1", "17"}, {"austin", "1", "15"},
        {"andrew", "1", "15"}, {"mike", "1", "14"}, {"alex", "1", "14"}, {"chris", "1", "13"},
        {"taylor", "1", "13"}, {"michael", "1", "12"}, {"jr", "1", "12"}, {"brandon", "1", "11"},
        {"david", "1", "11"}, {"aaron", "1", "11"}, {"anthony", "1", "11"}, {"garcia", "1", "11"},
        {"miguel", "1", "10"}, {"smith", "1", "9"}, {"drew", "1", "9"}, {"joe", "1", "9"},
        {"garrett", "1", "9"}, {"trevor", "1", "9"}, {"justin", "1", "9"}, {"daniel", "1", "9"},
        {"scott", "1", "8"}, {"kevin", "1", "8"}, {"bryan", "1", "8"}, {"adam", "1", "8"},
        {"anderson", "1", "8"}, {"jordan", "1", "8"}, {"castro", "1", "8"}, {"ramirez", "1", "7"},
        {"perez", "1", "7"}, {"james", "1", "7"}, {"dylan", "1", "7"}, {"zack", "1", "7"},
        {"luke", "1", "7"}, {"diaz", "1", "7"}, {"sam", "1", "7"}, {"martin", "1", "7"},
        {"carlos", "1", "7"}, {"sanchez", "1", "6"}, {"tommy", "1", "6"}, {"jason", "1", "6"},
        {"zach", "1", "6"}, {"sean", "1", "6"}, {"paul", "1", "6"}, {"john", "1", "6"},
        {"eric", "1", "6"}, {"cody", "1", "6"}, {"brad", "1", "6"}, {"max", "1", "6"},
        {"aj", "1", "6"}, {"jonathan", "1", "6"}, {"stephen", "1", "6"}, {"hernandez", "1", "6"},
        {"reyes", "1", "5"}, {"mitch", "1", "5"}, {"jorge", "1", "5"}, {"danny", "1", "5"},
        {"will", "1", "5"}, {"wade", "1", "5"}, {"seth", "1", "5"}, {"cole", "1", "5"},
        {"patrick", "1", "5"}, {"tanner", "1", "5"}, {"steven", "1", "5"}, {"rogers", "1", "5"},
        {"hunter", "1", "5"}, {"rodriguez", "1", "5"}, {"gonzalez", "1", "4"},
        {"santana", "1", "4"}, {"thompson", "1", "4"}, {"charlie", "1", "4"}, {"bradley", "1", "4"},
        {"pedro", "1", "4"}, {"lucas", "1", "4"}, {"lopez", "1", "4"}, {"jones", "1", "4"},
        {"jesse", "1", "4"}, {"corey", "1", "4"}, {"brett", "1", "4"}, {"blake", "1", "4"},
        {"chad", "1", "4"}, {"jon", "1", "4"}, {"ian", "1", "4"}, {"de", "1", "4"},
        {"christian", "1", "4"}, {"victor", "1", "4"}, {"tucker", "1", "4"}, {"travis", "1", "4"},
        {"robert", "1", "4"}, {"rafael", "1", "4"}, {"williams", "1", "4"}, {"guerra", "1", "4"},
        {"jackson", "1", "4"}, {"crawford", "1", "3"}, {"francisco", "1", "3"},
        {"cabrera", "1", "3"}, {"gregory", "1", "3"}, {"martinez", "1", "3"}, {"white", "1", "3"},
        {"urias", "1", "3"}, {"shane", "1", "3"}, {"rojas", "1", "3"}, {"riley", "1", "3"},
        {"ramon", "1", "3"}, {"pablo", "1", "3"}, {"mejia", "1", "3"}, {"manny", "1", "3"},
        {"logan", "1", "3"}, {"lewis", "1", "3"}, {"kelly", "1", "3"}, {"jesus", "1", "3"},
        {"jacob", "1", "3"}, {"hicks", "1", "3"}, {"edwin", "1", "3"}, {"derek", "1", "3"},
        {"caleb", "1", "3"}, {"brian", "1", "3"}, {"brent", "1", "3"}, {"angel", "1", "3"},
        {"abreu", "1", "3"}, {"webb", "1", "3"}, {"tony", "1", "3"}, {"leon", "1", "3"},
        {"juan", "1", "3"}, {"joey", "1", "3"}, {"greg", "1", "3"}, {"evan", "1", "3"},
        {"alec", "1", "3"}, {"zac", "1", "3"}, {"tim", "1", "3"}, {"ben", "1", "3"},
        {"tj", "1", "3"}, {"jd", "1", "3"}, {"contreras", "1", "3"}, {"peralta", "1", "3"},
        {"walker", "1", "3"}, {"valdez", "1", "3"}, {"thomas", "1", "3"}, {"suarez", "1", "3"},
        {"ronald", "1", "3"}, {"nelson", "1", "3"}, {"miller", "1", "3"}, {"keller", "1", "3"},
        {"alexander", "1", "3"}, {"dustin", "1", "3"}, {"dillon", "1", "3"}, {"corbin", "1", "3"},
        {"connor", "1", "3"}, {"barnes", "1", "3"}, {"andres", "1", "3"}, {"adrian", "1", "3"},
        {"spencer", "1", "3"}, {"santiago", "1", "2"}, {"sandoval", "1", "2"},
        {"cristian", "1", "2"}, {"castellanos", "1", "2"}, {"donovan", "1", "2"},
        {"dominic", "1", "2"}, {"domingo", "1", "2"}, {"fletcher", "1", "2"},
        {"sheffield", "1", "2"}, {"fernandez", "1", "2"}, {"severino", "1", "2"},
        {"daulton", "1", "2"}, {"richard", "1", "2"}, {"emmanuel", "1", "2"}, {"holland", "1", "2"},
        {"machado", "1", "2"}, {"chapman", "1", "2"}, {"alcantara", "1", "2"},
        {"cameron", "1", "2"}, {"calhoun", "1", "2"}, {"humberto", "1", "2"},
        {"peterson", "1", "2"}, {"gurriel", "1", "2"}, {"mauricio", "1", "2"},
        {"griffin", "1", "2"}, {"fernando", "1", "2"}, {"wyatt", "1", "2"}, {"wells", "1", "2"},
        {"trent", "1", "2"}, {"sandy", "1", "2"}, {"rivas", "1", "2"}, {"randy", "1", "2"},
        {"ramos", "1", "2"}, {"raley", "1", "2"}, {"ponce", "1", "2"}, {"peter", "1", "2"},
        {"nunez", "1", "2"}, {"moran", "1", "2"}, {"moore", "1", "2"}, {"mills", "1", "2"},
        {"marte", "1", "2"}, {"lance", "1", "2"}, {"julio", "1", "2"}, {"jimmy", "1", "2"},
        {"jared", "1", "2"}, {"isaac", "1", "2"}, {"gavin", "1", "2"}, {"evans", "1", "2"},
        {"elvis", "1", "2"}, {"duffy", "1", "2"}, {"devin", "1", "2"}, {"davis", "1", "2"},
        {"craig", "1", "2"}, {"colin", "1", "2"}, {"chase", "1", "2"}, {"casey", "1", "2"},
        {"bruce", "1", "2"}, {"brady", "1", "2"}, {"bobby", "1", "2"}, {"avila", "1", "2"},
        {"andre", "1", "2"}, {"allen", "1", "2"}, {"adams", "1", "2"}, {"robertson", "1", "2"},
        {"gilbert", "1", "2"}, {"yoan", "1", "2"}, {"wood", "1", "2"}, {"wong", "1", "2"},
        {"soto", "1", "2"}, {"ryne", "1", "2"}, {"ross", "1", "2"}, {"pozo", "1", "2"},
        {"pete", "1", "2"}, {"nola", "1", "2"}, {"mark", "1", "2"}, {"lowe", "1", "2"},
        {"long", "1", "2"}, {"king", "1", "2"}, {"josé", "1", "2"}, {"jeff", "1", "2"},
        {"javy", "1", "2"}, {"jace", "1", "2"}, {"hyun", "1", "2"}, {"díaz", "1", "2"},
        {"hill", "1", "2"}, {"gray", "1", "2"}, {"gabe", "1", "2"}, {"erik", "1", "2"},
        {"dean", "1", "2"}, {"andy", "1", "2"}, {"wil", "1", "2"}, {"may", "1", "2"},
        {"kim", "1", "2"}, {"jay", "1", "2"}, {"fry", "1", "2"}, {"eli", "1", "2"},
        {"dan", "1", "2"}, {"chi", "1", "2"}, {"cal", "1", "2"}, {"yu", "1", "2"}, {"la", "1", "2"},
        {"jt", "1", "2"}, {"dj", "1", "2"}, {"lambert", "1", "2"}, {"polanco", "1", "2"},
        {"vladimir", "1", "2"}, {"freeman", "1", "2"}, {"frazier", "1", "2"}, {"perdomo", "1", "2"},
        {"peacock", "1", "2"}, {"zimmer", "1", "2"}, {"wright", "1", "2"}, {"wilmer", "1", "2"},
        {"paredes", "1", "2"}, {"warren", "1", "2"}, {"wander", "1", "2"}, {"antonio", "1", "2"},
        {"alvarez", "1", "2"}, {"sergio", "1", "2"}, {"seager", "1", "2"}, {"santos", "1", "2"},
        {"almonte", "1", "2"}, {"alberto", "1", "2"}, {"rondon", "1", "2"}, {"romine", "1", "2"},
        {"romero", "1", "2"}, {"robbie", "1", "2"}, {"oviedo", "1", "2"}, {"ortega", "1", "2"},
        {"stephenson", "1", "2"}, {"oliver", "1", "2"}, {"aguilar", "1", "2"}, {"murphy", "1", "2"},
        {"morgan", "1", "2"}, {"mickey", "1", "2"}, {"megill", "1", "2"}, {"marcus", "1", "2"},
        {"manuel", "1", "2"}, {"keegan", "1", "2"}, {"junior", "1", "2"}, {"julian", "1", "2"},
        {"jansen", "1", "2"}, {"hector", "1", "2"}, {"harvey", "1", "2"}, {"harper", "1", "2"},
        {"harold", "1", "2"}, {"german", "1", "2"}, {"fulmer", "1", "2"}, {"franco", "1", "2"},
        {"flores", "1", "2"}, {"farmer", "1", "2"}, {"edward", "1", "2"}, {"devers", "1", "2"},
        {"darren", "1", "2"}, {"cooper", "1", "2"}, {"clarke", "1", "2"}, {"zimmermann", "1", "2"},
        {"carson", "1", "2"}, {"barlow", "1", "2"}, {"bailey", "1", "2"}, {"albert", "1", "2"},
        {"johnson", "1", "2"}, {"espinal", "1", "2"}, {"phillips", "1", "2"}, {"jimenez", "1", "2"},
        {"swanson", "1", "2"}, {"stewart", "1", "2"}, {"maldonado", "1", "1"},
        {"norwood", "1", "1"}, {"gregorius", "1", "1"}, {"nogosek", "1", "1"},
        {"gonzales", "1", "1"}, {"santillan", "1", "1"}, {"gonsolin", "1", "1"},
        {"santander", "1", "1"}, {"simmons", "1", "1"}, {"alvarado", "1", "1"},
        {"naughton", "1", "1"}, {"sheldon", "1", "1"}, {"odorizzi", "1", "1"},
        {"dunning", "1", "1"}, {"bumgarner", "1", "1"}, {"eshelman", "1", "1"},
        {"stallings", "1", "1"}, {"margevicius", "1", "1"}, {"seabold", "1", "1"},
        {"nivaldo", "1", "1"}, {"nittoli", "1", "1"}, {"salvador", "1", "1"},
        {"criswell", "1", "1"}, {"crismatt", "1", "1"}, {"morimando", "1", "1"},
        {"crichton", "1", "1"}, {"schrock", "1", "1"}, {"schmidt", "1", "1"},
        {"sanmartin", "1", "1"}, {"lemahieu", "1", "1"}, {"lobstein", "1", "1"},
        {"shoemaker", "1", "1"}, {"plawecki", "1", "1"}, {"saucedo", "1", "1"},
        {"sandlin", "1", "1"}, {"sampson", "1", "1"}, {"betances", "1", "1"},
        {"davidson", "1", "1"}, {"mccaughan", "1", "1"}, {"loaisiga", "1", "1"},
        {"newsome", "1", "1"}, {"newcomb", "1", "1"}, {"neidert", "1", "1"}, {"mckenzie", "1", "1"},
        {"bernardo", "1", "1"}, {"allgeyer", "1", "1"}, {"stratton", "1", "1"},
        {"bogaerts", "1", "1"}, {"klobosits", "1", "1"}, {"goldschmidt", "1", "1"},
        {"narvaez", "1", "1"}, {"reidfoley", "1", "1"}, {"benjamin", "1", "1"},
        {"chisholm", "1", "1"}, {"chirinos", "1", "1"}, {"diekman", "1", "1"},
        {"dickson", "1", "1"}, {"bellatti", "1", "1"}, {"deshields", "1", "1"},
        {"kinerfalefa", "1", "1"}, {"flaherty", "1", "1"}, {"mccarthy", "1", "1"},
        {"mountcastle", "1", "1"}, {"eickhoff", "1", "1"}, {"vogelbach", "1", "1"},
        {"hutchison", "1", "1"}, {"detmers", "1", "1"}, {"donaldson", "1", "1"},
        {"stevenson", "1", "1"}, {"kittredge", "1", "1"}, {"nootbaar", "1", "1"},
        {"celestino", "1", "1"}, {"darvish", "1", "1"}, {"darnaud", "1", "1"},
        {"mullins", "1", "1"}, {"thornton", "1", "1"}, {"rougned", "1", "1"}, {"rosscup", "1", "1"},
        {"rosario", "1", "1"}, {"newberry", "1", "1"}, {"rodolfo", "1", "1"}, {"rodgers", "1", "1"},
        {"roberto", "1", "1"}, {"velazquez", "1", "1"}, {"winkler", "1", "1"},
        {"willson", "1", "1"}, {"william", "1", "1"}, {"widener", "1", "1"},
        {"blackburn", "1", "1"}, {"staumont", "1", "1"}, {"whitley", "1", "1"},
        {"wheeler", "1", "1"}, {"wojciechowski", "1", "1"}, {"trammell", "1", "1"},
        {"seranthony", "1", "1"}, {"huascar", "1", "1"}, {"syndergaard", "1", "1"},
        {"moronta", "1", "1"}, {"morejón", "1", "1"}, {"mondesi", "1", "1"}, {"moncada", "1", "1"},
        {"hermosillo", "1", "1"}, {"webster", "1", "1"}, {"jhonathan", "1", "1"},
        {"thielbar", "1", "1"}, {"deichmann", "1", "1"}, {"ridings", "1", "1"},
        {"vierling", "1", "1"}, {"lindblom", "1", "1"}, {"boxberger", "1", "1"},
        {"watkins", "1", "1"}, {"andrelton", "1", "1"}, {"wallach", "1", "1"},
        {"giovanny", "1", "1"}, {"devenski", "1", "1"}, {"gilbreath", "1", "1"},
        {"gsellman", "1", "1"}, {"hoskins", "1", "1"}, {"rengifo", "1", "1"}, {"renfroe", "1", "1"},
        {"holaday", "1", "1"}, {"hoffman", "1", "1"}, {"hoerner", "1", "1"}, {"reddick", "1", "1"},
        {"mikolas", "1", "1"}, {"crochet", "1", "1"}, {"álvarez", "1", "1"}, {"gilberto", "1", "1"},
        {"palacios", "1", "1"}, {"kiermaier", "1", "1"}, {"raleigh", "1", "1"},
        {"cousins", "1", "1"}, {"cordero", "1", "1"}, {"misiewicz", "1", "1"},
        {"merrill", "1", "1"}, {"mercado", "1", "1"}, {"coonrod", "1", "1"}, {"mendick", "1", "1"},
        {"collins", "1", "1"}, {"coleman", "1", "1"}, {"jankowski", "1", "1"},
        {"meadows", "1", "1"}, {"gonsalves", "1", "1"}, {"clippard", "1", "1"},
        {"merryweather", "1", "1"}, {"arozarena", "1", "1"}, {"mcmahon", "1", "1"},
        {"mckenna", "1", "1"}, {"mcguire", "1", "1"}, {"mcgowin", "1", "1"},
        {"dominguez", "1", "1"}, {"clement", "1", "1"}, {"northcraft", "1", "1"},
        {"clayton", "1", "1"}, {"claudio", "1", "1"}, {"mazeika", "1", "1"}, {"demarcus", "1", "1"},
        {"musgrove", "1", "1"}, {"mattson", "1", "1"}, {"matthew", "1", "1"}, {"martini", "1", "1"},
        {"marquez", "1", "1"}, {"marchan", "1", "1"}, {"marcell", "1", "1"}, {"marcano", "1", "1"},
        {"manning", "1", "1"}, {"mancini", "1", "1"}, {"toussaint", "1", "1"},
        {"madison", "1", "1"}, {"heyward", "1", "1"}, {"herrera", "1", "1"}, {"heredia", "1", "1"},
        {"hentges", "1", "1"}, {"hendrix", "1", "1"}, {"helsley", "1", "1"}, {"heasley", "1", "1"},
        {"cisnero", "1", "1"}, {"haseong", "1", "1"}, {"hartman", "1", "1"}, {"haniger", "1", "1"},
        {"hanhold", "1", "1"}, {"hampson", "1", "1"}, {"jefferies", "1", "1"},
        {"quijada", "1", "1"}, {"senzatela", "1", "1"}, {"jurickson", "1", "1"},
        {"bichette", "1", "1"}, {"moustakas", "1", "1"}, {"mckinstry", "1", "1"},
        {"pomeranz", "1", "1"}, {"castano", "1", "1"}, {"carlton", "1", "1"}, {"carlson", "1", "1"},
        {"canning", "1", "1"}, {"baldonado", "1", "1"}, {"brubaker", "1", "1"},
        {"grossman", "1", "1"}, {"petricka", "1", "1"}, {"vincent", "1", "1"},
        {"benintendi", "1", "1"}, {"middleton", "1", "1"}, {"gustave", "1", "1"},
        {"brothers", "1", "1"}, {"brosseau", "1", "1"}, {"guilmet", "1", "1"},
        {"olivares", "1", "1"}, {"lowther", "1", "1"}, {"lourdes", "1", "1"}, {"lorenzo", "1", "1"},
        {"verdugo", "1", "1"}, {"gallagher", "1", "1"}, {"mathisen", "1", "1"},
        {"grisham", "1", "1"}, {"grichuk", "1", "1"}, {"yusmeiro", "1", "1"}, {"greinke", "1", "1"},
        {"greiner", "1", "1"}, {"grayson", "1", "1"}, {"grandal", "1", "1"}, {"llovera", "1", "1"},
        {"giancarlo", "1", "1"}, {"marshall", "1", "1"}, {"vazquez", "1", "1"},
        {"vasquez", "1", "1"}, {"valaika", "1", "1"}, {"buehler", "1", "1"}, {"buchter", "1", "1"},
        {"mcfarland", "1", "1"}, {"schreiber", "1", "1"}, {"goodwin", "1", "1"},
        {"goodrum", "1", "1"}, {"merrifield", "1", "1"}, {"littell", "1", "1"},
        {"brusdar", "1", "1"}, {"brogdon", "1", "1"}, {"britton", "1", "1"}, {"brinson", "1", "1"},
        {"breyvic", "1", "1"}, {"brennan", "1", "1"}, {"brendan", "1", "1"}, {"bregman", "1", "1"},
        {"brebbia", "1", "1"}, {"mantiply", "1", "1"}, {"braxton", "1", "1"}, {"brasier", "1", "1"},
        {"brandyn", "1", "1"}, {"turnbull", "1", "1"}, {"dinelson", "1", "1"},
        {"harrison", "1", "1"}, {"zuber", "1", "1"}, {"zeuch", "1", "1"}, {"zerpa", "1", "1"},
        {"yusei", "1", "1"}, {"young", "1", "1"}, {"yonny", "1", "1"}, {"yohel", "1", "1"},
        {"yohan", "1", "1"}, {"yency", "1", "1"}, {"yefry", "1", "1"}, {"yandy", "1", "1"},
        {"wynns", "1", "1"}, {"willi", "1", "1"}, {"wieck", "1", "1"}, {"wantz", "1", "1"},
        {"walsh", "1", "1"}, {"walls", "1", "1"}, {"wacha", "1", "1"}, {"gleyber", "1", "1"},
        {"votto", "1", "1"}, {"vinny", "1", "1"}, {"vidal", "1", "1"}, {"vesia", "1", "1"},
        {"urena", "1", "1"}, {"upton", "1", "1"}, {"uceta", "1", "1"}, {"tylor", "1", "1"},
        {"trout", "1", "1"}, {"trejo", "1", "1"}, {"touki", "1", "1"}, {"tomas", "1", "1"},
        {"pérez", "1", "1"}, {"terry", "1", "1"}, {"tejay", "1", "1"}, {"tatis", "1", "1"},
        {"tarik", "1", "1"}, {"tapia", "1", "1"}, {"suter", "1", "1"}, {"suero", "1", "1"},
        {"strop", "1", "1"}, {"story", "1", "1"}, {"steve", "1", "1"}, {"souza", "1", "1"},
        {"sonny", "1", "1"}, {"solak", "1", "1"}, {"snell", "1", "1"}, {"snead", "1", "1"},
        {"smyly", "1", "1"}, {"short", "1", "1"}, {"shogo", "1", "1"}, {"shawn", "1", "1"},
        {"núñez", "1", "1"}, {"sborz", "1", "1"}, {"sammy", "1", "1"}, {"rowen", "1", "1"},
        {"rowan", "1", "1"}, {"rosso", "1", "1"}, {"roman", "1", "1"}, {"rodon", "1", "1"},
        {"robel", "1", "1"}, {"roark", "1", "1"}, {"glasnow", "1", "1"}, {"reiss", "1", "1"},
        {"reese", "1", "1"}, {"quinn", "1", "1"}, {"lópez", "1", "1"}, {"price", "1", "1"},
        {"posey", "1", "1"}, {"petit", "1", "1"}, {"pavin", "1", "1"}, {"parra", "1", "1"},
        {"paolo", "1", "1"}, {"pagan", "1", "1"}, {"packy", "1", "1"}, {"pache", "1", "1"},
        {"ozzie", "1", "1"}, {"ozuna", "1", "1"}, {"osich", "1", "1"}, {"oscar", "1", "1"},
        {"olson", "1", "1"}, {"oliva", "1", "1"}, {"okert", "1", "1"}, {"nomar", "1", "1"},
        {"nolin", "1", "1"}, {"nolan", "1", "1"}, {"nimmo", "1", "1"}, {"nicky", "1", "1"},
        {"neuse", "1", "1"}, {"neris", "1", "1"}, {"nance", "1", "1"}, {"nabil", "1", "1"},
        {"myers", "1", "1"}, {"graterol", "1", "1"}, {"munoz", "1", "1"}, {"muncy", "1", "1"},
        {"minor", "1", "1"}, {"miley", "1", "1"}, {"miles", "1", "1"}, {"carpenter", "1", "1"},
        {"menez", "1", "1"}, {"mella", "1", "1"}, {"mears", "1", "1"}, {"means", "1", "1"},
        {"mcrae", "1", "1"}, {"mcgee", "1", "1"}, {"mazza", "1", "1"}, {"mayza", "1", "1"},
        {"maton", "1", "1"}, {"mason", "1", "1"}, {"marsh", "1", "1"}, {"marco", "1", "1"},
        {"maile", "1", "1"}, {"mahle", "1", "1"}, {"maeda", "1", "1"}, {"lynch", "1", "1"},
        {"lyles", "1", "1"}, {"louis", "1", "1"}, {"lewin", "1", "1"}, {"leury", "1", "1"},
        {"leone", "1", "1"}, {"leody", "1", "1"}, {"lauer", "1", "1"}, {"lange", "1", "1"},
        {"lamet", "1", "1"}, {"kwang", "1", "1"}, {"kowar", "1", "1"}, {"kolby", "1", "1"},
        {"kohei", "1", "1"}, {"knehr", "1", "1"}, {"knapp", "1", "1"}, {"kirby", "1", "1"},
        {"keury", "1", "1"}, {"ketel", "1", "1"}, {"keone", "1", "1"}, {"kenta", "1", "1"},
        {"kaleb", "1", "1"}, {"junis", "1", "1"}, {"judge", "1", "1"}, {"joyce", "1", "1"},
        {"jordy", "1", "1"}, {"jonah", "1", "1"}, {"johan", "1", "1"}, {"jiman", "1", "1"},
        {"jerad", "1", "1"}, {"jefry", "1", "1"}, {"jakob", "1", "1"}, {"jaime", "1", "1"},
        {"isiah", "1", "1"}, {"isbel", "1", "1"}, {"irvin", "1", "1"}, {"india", "1", "1"},
        {"houck", "1", "1"}, {"hiura", "1", "1"}, {"henry", "1", "1"}, {"heath", "1", "1"},
        {"hearn", "1", "1"}, {"hayes", "1", "1"}, {"hatch", "1", "1"}, {"hardy", "1", "1"},
        {"hader", "1", "1"}, {"haase", "1", "1"}, {"green", "1", "1"}, {"grant", "1", "1"},
        {"godoy", "1", "1"}, {"glenn", "1", "1"}, {"garza", "1", "1"}, {"fried", "1", "1"},
        {"frias", "1", "1"}, {"foley", "1", "1"}, {"floro", "1", "1"}, {"fiers", "1", "1"},
        {"felix", "1", "1"}, {"fedde", "1", "1"}, {"faria", "1", "1"}, {"ervin", "1", "1"},
        {"ernie", "1", "1"}, {"erick", "1", "1"}, {"enoli", "1", "1"}, {"engel", "1", "1"},
        {"ender", "1", "1"}, {"ellis", "1", "1"}, {"elias", "1", "1"}, {"ehire", "1", "1"},
        {"eflin", "1", "1"}, {"edman", "1", "1"}, {"edgar", "1", "1"}, {"duran", "1", "1"},
        {"dubon", "1", "1"}, {"duane", "1", "1"}, {"drury", "1", "1"}, {"doval", "1", "1"},
        {"dolis", "1", "1"}, {"deivi", "1", "1"}, {"dauri", "1", "1"}, {"darin", "1", "1"},
        {"damon", "1", "1"}, {"cueto", "1", "1"}, {"crowe", "1", "1"}, {"crick", "1", "1"},
        {"clint", "1", "1"}, {"clase", "1", "1"}, {"chang", "1", "1"}, {"cesar", "1", "1"},
        {"cease", "1", "1"}, {"cavan", "1", "1"}, {"canha", "1", "1"}, {"byron", "1", "1"},
        {"burns", "1", "1"}, {"burch", "1", "1"}, {"bundy", "1", "1"}, {"bubic", "1", "1"},
        {"bryce", "1", "1"}, {"brown", "1", "1"}, {"brody", "1", "1"}, {"brock", "1", "1"},
        {"brice", "1", "1"}, {"brach", "1", "1"}, {"billy", "1", "1"}, {"betts", "1", "1"},
        {"berti", "1", "1"}, {"beede", "1", "1"}, {"beaty", "1", "1"}, {"bauer", "1", "1"},
        {"baker", "1", "1"}, {"bader", "1", "1"}, {"asher", "1", "1"}, {"ashby", "1", "1"},
        {"arauz", "1", "1"}, {"alexy", "1", "1"}, {"akeem", "1", "1"}, {"ahmed", "1", "1"},
        {"adell", "1", "1"}, {"acuna", "1", "1"}, {"inciarte", "1", "1"}, {"bukauskas", "1", "1"},
        {"spitzbarth", "1", "1"}, {"bostick", "1", "1"}, {"borucki", "1", "1"},
        {"bolanos", "1", "1"}, {"kaprielian", "1", "1"}, {"gittens", "1", "1"},
        {"castillo", "1", "1"}, {"giolito", "1", "1"}, {"gimenez", "1", "1"},
        {"yastrzemski", "1", "1"}, {"carrasco", "1", "1"}, {"yuli", "1", "1"}, {"ynoa", "1", "1"},
        {"yang", "1", "1"}, {"wily", "1", "1"}, {"wick", "1", "1"}, {"whit", "1", "1"},
        {"ward", "1", "1"}, {"voth", "1", "1"}, {"voit", "1", "1"}, {"vest", "1", "1"},
        {"trey", "1", "1"}, {"tres", "1", "1"}, {"topa", "1", "1"}, {"todd", "1", "1"},
        {"tate", "1", "1"}, {"sosa", "1", "1"}, {"siri", "1", "1"}, {"sims", "1", "1"},
        {"shed", "1", "1"}, {"shea", "1", "1"}, {"shaw", "1", "1"}, {"seby", "1", "1"},
        {"sano", "1", "1"}, {"sale", "1", "1"}, {"ruiz", "1", "1"}, {"rony", "1", "1"},
        {"romy", "1", "1"}, {"romo", "1", "1"}, {"roel", "1", "1"}, {"rios", "1", "1"},
        {"rhys", "1", "1"}, {"reid", "1", "1"}, {"reed", "1", "1"}, {"pina", "1", "1"},
        {"phil", "1", "1"}, {"pham", "1", "1"}, {"pena", "1", "1"}, {"owen", "1", "1"},
        {"otto", "1", "1"}, {"omar", "1", "1"}, {"odor", "1", "1"}, {"oday", "1", "1"},
        {"ober", "1", "1"}, {"noah", "1", "1"}, {"niko", "1", "1"}, {"nido", "1", "1"},
        {"nico", "1", "1"}, {"nate", "1", "1"}, {"moll", "1", "1"}, {"mize", "1", "1"},
        {"matz", "1", "1"}, {"lynn", "1", "1"}, {"lugo", "1", "1"}, {"loup", "1", "1"},
        {"ljay", "1", "1"}, {"liam", "1", "1"}, {"latz", "1", "1"}, {"lars", "1", "1"},
        {"lail", "1", "1"}, {"kurt", "1", "1"}, {"kuhl", "1", "1"}, {"krol", "1", "1"},
        {"kris", "1", "1"}, {"kole", "1", "1"}, {"kohl", "1", "1"}, {"kodi", "1", "1"},
        {"kirk", "1", "1"}, {"kent", "1", "1"}, {"kemp", "1", "1"}, {"kela", "1", "1"},
        {"kean", "1", "1"}, {"junk", "1", "1"}, {"jong", "1", "1"}, {"jojo", "1", "1"},
        {"joan", "1", "1"}, {"jhon", "1", "1"}, {"jean", "1", "1"}, {"jazz", "1", "1"},
        {"jack", "1", "1"}, {"ivey", "1", "1"}, {"isan", "1", "1"}, {"hoyt", "1", "1"},
        {"holt", "1", "1"}, {"hoby", "1", "1"}, {"heim", "1", "1"}, {"head", "1", "1"},
        {"hays", "1", "1"}, {"happ", "1", "1"}, {"hans", "1", "1"}, {"hale", "1", "1"},
        {"hahn", "1", "1"}, {"gose", "1", "1"}, {"gary", "1", "1"}, {"ford", "1", "1"},
        {"enns", "1", "1"}, {"eloy", "1", "1"}, {"eddy", "1", "1"}, {"dunn", "1", "1"},
        {"dohy", "1", "1"}, {"difo", "1", "1"}, {"didi", "1", "1"}, {"daza", "1", "1"},
        {"dane", "1", "1"}, {"dahl", "1", "1"}, {"curt", "1", "1"}, {"cruz", "1", "1"},
        {"cron", "1", "1"}, {"cory", "1", "1"}, {"cobb", "1", "1"}, {"clay", "1", "1"},
        {"choi", "1", "1"}, {"chaz", "1", "1"}, {"chas", "1", "1"}, {"cave", "1", "1"},
        {"cain", "1", "1"}, {"bush", "1", "1"}, {"burr", "1", "1"}, {"buck", "1", "1"},
        {"boyd", "1", "1"}, {"bote", "1", "1"}, {"bohm", "1", "1"}, {"belt", "1", "1"},
        {"bell", "1", "1"}, {"bass", "1", "1"}, {"bard", "1", "1"}, {"baez", "1", "1"},
        {"amir", "1", "1"}, {"amed", "1", "1"}, {"alek", "1", "1"}, {"alan", "1", "1"},
        {"akin", "1", "1"}, {"akil", "1", "1"}, {"adon", "1", "1"}, {"abad", "1", "1"},
        {"wes", "1", "1"}, {"tom", "1", "1"}, {"ryu", "1", "1"}, {"ruf", "1", "1"},
        {"roe", "1", "1"}, {"rob", "1", "1"}, {"rex", "1", "1"}, {"rea", "1", "1"},
        {"ray", "1", "1"}, {"puk", "1", "1"}, {"pop", "1", "1"}, {"pat", "1", "1"},
        {"ort", "1", "1"}, {"mac", "1", "1"}, {"lux", "1", "1"}, {"lou", "1", "1"},
        {"lee", "1", "1"}, {"law", "1", "1"}, {"kay", "1", "1"}, {"jin", "1", "1"},
        {"jed", "1", "1"}, {"jax", "1", "1"}, {"gio", "1", "1"}, {"gil", "1", "1"},
        {"dom", "1", "1"}, {"del", "1", "1"}, {"daz", "1", "1"}, {"cam", "1", "1"},
        {"baz", "1", "1"}, {"art", "1", "1"}, {"ty", "1", "1"}, {"rj", "1", "1"}, {"jp", "1", "1"},
        {"jo", "1", "1"}, {"jc", "1", "1"}, {"jb", "1", "1"}, {"cj", "1", "1"}, {"bo", "1", "1"},
        {"a", "1", "1"}, {"caratini", "1", "1"}, {"hamilton", "1", "1"}, {"campusano", "1", "1"},
        {"brantley", "1", "1"}, {"blewett", "1", "1"}, {"larnach", "1", "1"}, {"lamonte", "1", "1"},
        {"woodruff", "1", "1"}, {"woodford", "1", "1"}, {"lagares", "1", "1"},
        {"gerardo", "1", "1"}, {"geraldo", "1", "1"}, {"castellani", "1", "1"},
        {"rortvedt", "1", "1"}, {"genesis", "1", "1"}, {"sittinger", "1", "1"},
        {"dietrich", "1", "1"}, {"biagini", "1", "1"}, {"hyeonjong", "1", "1"},
        {"campbell", "1", "1"}, {"lavarnway", "1", "1"}, {"madrigal", "1", "1"},
        {"camarena", "1", "1"}, {"urshela", "1", "1"}, {"urquidy", "1", "1"},
        {"reynolds", "1", "1"}, {"reynaldo", "1", "1"}, {"stripling", "1", "1"},
        {"gausman", "1", "1"}, {"garneau", "1", "1"}, {"garlick", "1", "1"}, {"gardner", "1", "1"},
        {"haggerty", "1", "1"}, {"moreland", "1", "1"}, {"bemboom", "1", "1"},
        {"beasley", "1", "1"}, {"piscotty", "1", "1"}, {"tucupita", "1", "1"},
        {"aristides", "1", "1"}, {"preston", "1", "1"}, {"pressly", "1", "1"},
        {"bazardo", "1", "1"}, {"baumann", "1", "1"}, {"bassitt", "1", "1"}, {"barrero", "1", "1"},
        {"barrera", "1", "1"}, {"barreda", "1", "1"}, {"baragar", "1", "1"},
        {"cronenworth", "1", "1"}, {"fairbanks", "1", "1"}, {"coulombe", "1", "1"},
        {"pollock", "1", "1"}, {"strasburg", "1", "1"}, {"kranick", "1", "1"},
        {"yamamoto", "1", "1"}, {"wainwright", "1", "1"}, {"smeltzer", "1", "1"},
        {"mercedes", "1", "1"}, {"holloway", "1", "1"}, {"fuentes", "1", "1"},
        {"refsnyder", "1", "1"}, {"kintzler", "1", "1"}, {"kolarek", "1", "1"},
        {"koerner", "1", "1"}, {"robinson", "1", "1"}, {"pivetta", "1", "1"}, {"knizner", "1", "1"},
        {"conforto", "1", "1"}, {"phillip", "1", "1"}, {"freddie", "1", "1"}, {"franmil", "1", "1"},
        {"frankie", "1", "1"}, {"franchy", "1", "1"}, {"framber", "1", "1"},
        {"kirilloff", "1", "1"}, {"cleavinger", "1", "1"}, {"avisail", "1", "1"},
        {"sherriff", "1", "1"}, {"gutiérrez", "1", "1"}, {"finnegan", "1", "1"},
        {"melancon", "1", "1"}, {"peguero", "1", "1"}, {"zunino", "1", "1"}, {"pearson", "1", "1"},
        {"schebler", "1", "1"}, {"zavala", "1", "1"}, {"zamora", "1", "1"}, {"kikuchi", "1", "1"},
        {"kieboom", "1", "1"}, {"kickham", "1", "1"}, {"yordan", "1", "1"}, {"weathers", "1", "1"},
        {"yermin", "1", "1"}, {"yennsy", "1", "1"}, {"yelich", "1", "1"}, {"aroldis", "1", "1"},
        {"yajure", "1", "1"}, {"yadier", "1", "1"}, {"yadiel", "1", "1"}, {"arihara", "1", "1"},
        {"hendriks", "1", "1"}, {"arenado", "1", "1"}, {"xander", "1", "1"}, {"sceroler", "1", "1"},
        {"fleming", "1", "1"}, {"wisdom", "1", "1"}, {"winker", "1", "1"}, {"willie", "1", "1"},
        {"paulino", "1", "1"}, {"wendle", "1", "1"}, {"welker", "1", "1"}, {"weigel", "1", "1"},
        {"weaver", "1", "1"}, {"walton", "1", "1"}, {"paddack", "1", "1"}, {"vosler", "1", "1"},
        {"vimael", "1", "1"}, {"villar", "1", "1"}, {"keuchel", "1", "1"}, {"kershaw", "1", "1"},
        {"vaughn", "1", "1"}, {"varsho", "1", "1"}, {"valera", "1", "1"}, {"adrianza", "1", "1"},
        {"kelenic", "1", "1"}, {"culberson", "1", "1"}, {"ottavino", "1", "1"},
        {"kebryan", "1", "1"}, {"bellinger", "1", "1"}, {"tyrone", "1", "1"},
        {"realmuto", "1", "1"}, {"andujar", "1", "1"}, {"turner", "1", "1"}, {"trayce", "1", "1"},
        {"torres", "1", "1"}, {"tomlin", "1", "1"}, {"tinoco", "1", "1"}, {"thorpe", "1", "1"},
        {"thairo", "1", "1"}, {"heineman", "1", "1"}, {"tayler", "1", "1"}, {"suzuki", "1", "1"},
        {"sulser", "1", "1"}, {"torreyes", "1", "1"}, {"stubbs", "1", "1"}, {"strahm", "1", "1"},
        {"stevie", "1", "1"}, {"stella", "1", "1"}, {"stefan", "1", "1"}, {"steele", "1", "1"},
        {"stassi", "1", "1"}, {"stanek", "1", "1"}, {"speier", "1", "1"}, {"solano", "1", "1"},
        {"sogard", "1", "1"}, {"yonathan", "1", "1"}, {"snyder", "1", "1"}, {"alzolay", "1", "1"},
        {"slater", "1", "1"}, {"skubal", "1", "1"}, {"singer", "1", "1"}, {"sierra", "1", "1"},
        {"shreve", "1", "1"}, {"shohei", "1", "1"}, {"sheets", "1", "1"}, {"sewald", "1", "1"},
        {"senzel", "1", "1"}, {"semien", "1", "1"}, {"segura", "1", "1"}, {"scrubb", "1", "1"},
        {"schoop", "1", "1"}, {"sadler", "1", "1"}, {"alfonso", "1", "1"}, {"aledmys", "1", "1"},
        {"alcides", "1", "1"}, {"rucker", "1", "1"}, {"rooker", "1", "1"}, {"romano", "1", "1"},
        {"robles", "1", "1"}, {"roansy", "1", "1"}, {"desclafani", "1", "1"},
        {"wittgren", "1", "1"}, {"rivero", "1", "1"}, {"rivera", "1", "1"}, {"richie", "1", "1"},
        {"reymin", "1", "1"}, {"rendon", "1", "1"}, {"renato", "1", "1"}, {"reiver", "1", "1"},
        {"raynel", "1", "1"}, {"ranger", "1", "1"}, {"randal", "1", "1"}, {"raisel", "1", "1"},
        {"rainey", "1", "1"}, {"raimel", "1", "1"}, {"akiyama", "1", "1"}, {"feltner", "1", "1"},
        {"profar", "1", "1"}, {"poteet", "1", "1"}, {"plutko", "1", "1"}, {"plesac", "1", "1"},
        {"pineda", "1", "1"}, {"pinder", "1", "1"}, {"pillar", "1", "1"}, {"pierce", "1", "1"},
        {"phelps", "1", "1"}, {"peters", "1", "1"}, {"peraza", "1", "1"}, {"paxton", "1", "1"},
        {"patton", "1", "1"}, {"patino", "1", "1"}, {"parker", "1", "1"}, {"owings", "1", "1"},
        {"oswalt", "1", "1"}, {"oneill", "1", "1"}, {"ohtani", "1", "1"}, {"ohearn", "1", "1"},
        {"ogrady", "1", "1"}, {"odubel", "1", "1"}, {"obrien", "1", "1"}, {"underwood", "1", "1"},
        {"newman", "1", "1"}, {"nestor", "1", "1"}, {"naylor", "1", "1"}, {"nathan", "1", "1"},
        {"naquin", "1", "1"}, {"blandino", "1", "1"}, {"nathaniel", "1", "1"},
        {"trivino", "1", "1"}, {"triston", "1", "1"}, {"muller", "1", "1"}, {"trevino", "1", "1"},
        {"treinen", "1", "1"}, {"blackmon", "1", "1"}, {"morton", "1", "1"}, {"moreta", "1", "1"},
        {"mookie", "1", "1"}, {"montas", "1", "1"}, {"moniak", "1", "1"}, {"molina", "1", "1"},
        {"minter", "1", "1"}, {"minaya", "1", "1"}, {"milone", "1", "1"}, {"milner", "1", "1"},
        {"meyers", "1", "1"}, {"mercer", "1", "1"}, {"medina", "1", "1"}, {"farrell", "1", "1"},
        {"mcneil", "1", "1"}, {"mchugh", "1", "1"}, {"mccann", "1", "1"}, {"mazara", "1", "1"},
        {"mayers", "1", "1"}, {"maybin", "1", "1"}, {"matzek", "1", "1"}, {"margot", "1", "1"},
        {"marcos", "1", "1"}, {"maples", "1", "1"}, {"manoah", "1", "1"}, {"manaea", "1", "1"},
        {"maikel", "1", "1"}, {"madero", "1", "1"}, {"machin", "1", "1"}, {"familia", "1", "1"},
        {"luetge", "1", "1"}, {"lowrie", "1", "1"}, {"lindor", "1", "1"}, {"lakins", "1", "1"},
        {"kutter", "1", "1"}, {"kremer", "1", "1"}, {"marmolejos", "1", "1"}, {"kopech", "1", "1"},
        {"konner", "1", "1"}, {"kolten", "1", "1"}, {"knight", "1", "1"}, {"knebel", "1", "1"},
        {"kluber", "1", "1"}, {"kinley", "1", "1"}, {"keynan", "1", "1"}, {"keston", "1", "1"},
        {"kervin", "1", "1"}, {"kepler", "1", "1"}, {"kenley", "1", "1"}, {"torrens", "1", "1"},
        {"kazmir", "1", "1"}, {"justus", "1", "1"}, {"jovani", "1", "1"}, {"joshua", "1", "1"},
        {"johnny", "1", "1"}, {"jharel", "1", "1"}, {"jewell", "1", "1"}, {"jeurys", "1", "1"},
        {"jeremy", "1", "1"}, {"jeimer", "1", "1"}, {"willians", "1", "1"}, {"javier", "1", "1"},
        {"jarren", "1", "1"}, {"jarred", "1", "1"}, {"jarlin", "1", "1"}, {"janson", "1", "1"},
        {"jannis", "1", "1"}, {"jandel", "1", "1"}, {"jahmai", "1", "1"}, {"jacoby", "1", "1"},
        {"jackie", "1", "1"}, {"acevedo", "1", "1"}, {"quantrill", "1", "1"}, {"ibáñez", "1", "1"},
        {"abraham", "1", "1"}, {"mitchell", "1", "1"}, {"hudson", "1", "1"}, {"howard", "1", "1"},
        {"houser", "1", "1"}, {"hosmer", "1", "1"}, {"dickerson", "1", "1"}, {"hernan", "1", "1"},
        {"hedges", "1", "1"}, {"harris", "1", "1"}, {"hanser", "1", "1"}, {"hammer", "1", "1"},
        {"guzman", "1", "1"}, {"guduan", "1", "1"}, {"gordon", "1", "1"}, {"gomber", "1", "1"},
        {"godley", "1", "1"}, {"ginkel", "1", "1"}, {"gibaut", "1", "1"}, {"gerrit", "1", "1"},
        {"george", "1", "1"}, {"garver", "1", "1"}, {"garcía", "1", "1"}, {"gallen", "1", "1"},
        {"honeywell", "1", "1"}, {"friedl", "1", "1"}, {"freddy", "1", "1"}, {"france", "1", "1"},
        {"fraley", "1", "1"}, {"fowler", "1", "1"}, {"foster", "1", "1"}, {"fortes", "1", "1"},
        {"flexen", "1", "1"}, {"falter", "1", "1"}, {"espino", "1", "1"}, {"erasmo", "1", "1"},
        {"emilio", "1", "1"}, {"eduard", "1", "1"}, {"dusten", "1", "1"}, {"dugger", "1", "1"},
        {"duggar", "1", "1"}, {"duffey", "1", "1"}, {"dozier", "1", "1"}, {"dobnak", "1", "1"},
        {"diplan", "1", "1"}, {"deolis", "1", "1"}, {"dellin", "1", "1"}, {"delino", "1", "1"},
        {"dejong", "1", "1"}, {"degrom", "1", "1"}, {"dayton", "1", "1"}, {"davies", "1", "1"},
        {"darien", "1", "1"}, {"dansby", "1", "1"}, {"dallas", "1", "1"}, {"dalbec", "1", "1"},
        {"dakota", "1", "1"}, {"steckenrider", "1", "1"}, {"lawrence", "1", "1"},
        {"curtis", "1", "1"}, {"crouse", "1", "1"}, {"cotton", "1", "1"}, {"cortes", "1", "1"},
        {"correa", "1", "1"}, {"conner", "1", "1"}, {"conley", "1", "1"}, {"colton", "1", "1"},
        {"colten", "1", "1"}, {"colome", "1", "1"}, {"collin", "1", "1"}, {"civale", "1", "1"},
        {"cishek", "1", "1"}, {"vanmeter", "1", "1"}, {"cionel", "1", "1"},
        {"higashioka", "1", "1"}, {"chavez", "1", "1"}, {"chasen", "1", "1"}, {"chacin", "1", "1"},
        {"lucchesi", "1", "1"}, {"hirokazu", "1", "1"}, {"cedric", "1", "1"}, {"casali", "1", "1"},
        {"carter", "1", "1"}, {"camilo", "1", "1"}, {"cahill", "1", "1"}, {"buxton", "1", "1"},
        {"butera", "1", "1"}, {"buster", "1", "1"}, {"burnes", "1", "1"}, {"burger", "1", "1"},
        {"bummer", "1", "1"}, {"brujan", "1", "1"}, {"bruihl", "1", "1"}, {"brooks", "1", "1"},
        {"brewer", "1", "1"}, {"brentz", "1", "1"}, {"brault", "1", "1"}, {"bowden", "1", "1"},
        {"bleier", "1", "1"}, {"blaine", "1", "1"}, {"biggio", "1", "1"}, {"bielak", "1", "1"},
        {"bieber", "1", "1"}, {"biddle", "1", "1"}, {"bergen", "1", "1"}, {"bender", "1", "1"},
        {"bednar", "1", "1"}, {"yarbrough", "1", "1"}, {"yasmani", "1", "1"}, {"yardley", "1", "1"},
        {"barria", "1", "1"}, {"baddoo", "1", "1"}, {"laureano", "1", "1"}, {"eugenio", "1", "1"},
        {"axford", "1", "1"}, {"avilan", "1", "1"}, {"arroyo", "1", "1"}, {"arraez", "1", "1"},
        {"archie", "1", "1"}, {"archer", "1", "1"}, {"aramis", "1", "1"}, {"aquino", "1", "1"},
        {"antone", "1", "1"}, {"andrus", "1", "1"}, {"altuve", "1", "1"}, {"alonso", "1", "1"},
        {"almora", "1", "1"}, {"allard", "1", "1"}, {"alford", "1", "1"}, {"alfaro", "1", "1"},
        {"guerrero", "1", "1"}, {"alcala", "1", "1"}, {"albies", "1", "1"}, {"albers", "1", "1"},
        {"alaniz", "1", "1"}, {"guenther", "1", "1"}, {"adrián", "1", "1"}, {"adonis", "1", "1"},
        {"adolis", "1", "1"}, {"adbert", "1", "1"}, {"abbott", "1", "1"}, {"teoscar", "1", "1"},
        {"teheran", "1", "1"}, {"cristopher", "1", "1"}, {"estrada", "1", "1"},
        {"estevez", "1", "1"}, {"escobar", "1", "1"}, {"darwinzon", "1", "1"},
        {"candelario", "1", "1"}, {"altavilla", "1", "1"}, {"taveras", "1", "1"},
        {"freeland", "1", "1"}, {"hilliard", "1", "1"}, {"tarpley", "1", "1"},
        {"taillon", "1", "1"}, {"taijuan", "1", "1"}, {"hendricks", "1", "1"},
        {"richards", "1", "1"}, {"eovaldi", "1", "1"}, {"iglesias", "1", "1"},
        {"enrique", "1", "1"}, {"foltynewicz", "1", "1"}, {"duplantier", "1", "1"},
        {"jhoulys", "1", "1"}, {"emanuel", "1", "1"}, {"montgomery", "1", "1"},
        {"frankoff", "1", "1"}, {"astudillo", "1", "1"}, {"elledge", "1", "1"},
        {"elieser", "1", "1"}, {"karinchak", "1", "1"}, {"alejandro", "1", "1"},
        {"meisinger", "1", "1"}, {"jeffrey", "1", "1"}, {"jeffers", "1", "1"},
        {"barnhart", "1", "1"}, {"springer", "1", "1"}, {"gallegos", "1", "1"},
        {"wilkerson", "1", "1"}, {"jameson", "1", "1"}, {"effross", "1", "1"},
        {"barraclough", "1", "1"}, {"guillorme", "1", "1"}, {"guillermo", "1", "1"},
        {"lovelady", "1", "1"}, {"mccutchen", "1", "1"}, {"eduardo", "1", "1"},
        {"mccullers", "1", "1"}, {"stroman", "1", "1"}, {"strider", "1", "1"},
        {"edmundo", "1", "1"}, {"hildenberger", "1", "1"}, {"stiever", "1", "1"},
        {"funkhouser", "1", "1"}, {"stephan", "1", "1"}, {"stashak", "1", "1"},
        {"starlin", "1", "1"}, {"stanton", "1", "1"}, {"stammen", "1", "1"},
        {"hernández", "1", "1"}, {"szapucki", "1", "1"}, {"lorenzen", "1", "1"},
        {"adalberto", "1", "1"}, {"zimmerman", "1", "1"}, {"springs", "1", "1"},
        {"spenser", "1", "1"}, {"magneuris", "1", "1"}, {"quackenbush", "1", "1"},
        {"solomon", "1", "1"}, {"gosselin", "1", "1"}, {"mccormick", "1", "1"},
        {"sawamura", "1", "1"}, {"longoria", "1", "1"}, {"sebastian", "1", "1"},
        {"mcclanahan", "1", "1"}, {"bettinger", "1", "1"}, {"slegers", "1", "1"},
        {"whitlock", "1", "1"}};

    for (File file : new File[] {ngramsCsv, ngramsXlsx}) {
      try (TabularWorksheetReader rows = SpreadsheetFactory.getInstance()
          .readActiveTabularWorksheet(() -> new FileInputStream(file))) {
        assertThat(rows.stream().map(row -> {
          return new String[] {
              row.findCellByColumnName("ngram").map(c -> c.getValue(String.class)).get(),
              row.findCellByColumnName("length").map(c -> c.getValue(Integer.class)).get()
                  .toString(),
              row.findCellByColumnName("count").map(c -> c.getValue(Integer.class)).get()
                  .toString()};
        }).toArray(String[][]::new), is(expected));
      }
    }
  }
}
