/*-
 * =================================LICENSE_START==================================
 * toolforge-ngrams-tool
 * ====================================SECTION=====================================
 * Copyright (C) 2022 - 2023 ToolForge
 * ====================================SECTION=====================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ==================================LICENSE_END===================================
 */
package io.toolforge.tool.ngrams;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import java.io.File;
import java.io.FileInputStream;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;
import org.junit.Test;
import com.google.common.io.Resources;
import com.sigpwned.tabular4j.SpreadsheetFactory;
import com.sigpwned.tabular4j.model.TabularWorksheetReader;
import io.toolforge.tool.ngrams.App.NgramCount;
import io.toolforge.toolforge4j.io.InputSource;
import io.toolforge.toolforge4j.io.OutputSink;

public class NgramsTest {
  @Test
  public void smokeTest() {
    List<NgramCount> ngrams = App
        .compute(Stream.of("Hello, world!", "Hello, Dolly!", "Say hello to my little friend!",
            "You had me at hello."), 1, 3)
        .sorted(Comparator.<NgramCount>naturalOrder().reversed()).toList();

    assertThat(ngrams, is(List.of(NgramCount.of("hello", 4), NgramCount.of("had me at", 1),
        NgramCount.of("hello world", 1), NgramCount.of("hello to my", 1),
        NgramCount.of("hello dolly", 1), NgramCount.of("say hello", 1),
        NgramCount.of("to my little", 1), NgramCount.of("world", 1), NgramCount.of("to my", 1),
        NgramCount.of("me at", 1), NgramCount.of("dolly", 1), NgramCount.of("you", 1),
        NgramCount.of("say", 1), NgramCount.of("had", 1), NgramCount.of("to", 1),
        NgramCount.of("my", 1), NgramCount.of("me", 1), NgramCount.of("at", 1),
        NgramCount.of("me at hello", 1), NgramCount.of("hello to", 1),
        NgramCount.of("little friend", 1), NgramCount.of("you had", 1), NgramCount.of("little", 1),
        NgramCount.of("had me", 1), NgramCount.of("friend", 1), NgramCount.of("say hello to", 1),
        NgramCount.of("my little", 1), NgramCount.of("at hello", 1), NgramCount.of("you had me", 1),
        NgramCount.of("my little friend", 1))));
  }

  @Test
  public void spreadsheetTest() throws Exception {
    File ngramsCsv = File.createTempFile("ngrams.", ".csv");
    ngramsCsv.deleteOnExit();

    File ngramsXlsx = File.createTempFile("ngrams.", ".xlsx");
    ngramsXlsx.deleteOnExit();

    Configuration configuration = new Configuration();
    configuration.data = new InputSource(Resources.getResource("mlb_players_2021.csv").toURI());
    configuration.minNgramLength = 1L;
    configuration.maxNgramLength = 1L;
    configuration.textColumnName = "Name";
    configuration.ngramsCsv = new OutputSink(ngramsCsv.toURI());
    configuration.ngramsXlsx = new OutputSink(ngramsXlsx.toURI());

    App.main(configuration);

    String[][] expected = new String[][] {{"ryan", "24"}, {"kyle", "24"}, {"nick", "22"},
        {"jose", "20"}, {"tyler", "19"}, {"luis", "18"}, {"jake", "18"}, {"matt", "17"},
        {"josh", "17"}, {"austin", "15"}, {"andrew", "15"}, {"mike", "14"}, {"alex", "14"},
        {"chris", "13"}, {"taylor", "13"}, {"michael", "12"}, {"jr", "12"}, {"brandon", "11"},
        {"david", "11"}, {"aaron", "11"}, {"anthony", "11"}, {"garcia", "11"}, {"miguel", "10"},
        {"smith", "9"}, {"drew", "9"}, {"joe", "9"}, {"garrett", "9"}, {"trevor", "9"},
        {"justin", "9"}, {"daniel", "9"}, {"scott", "8"}, {"kevin", "8"}, {"bryan", "8"},
        {"adam", "8"}, {"anderson", "8"}, {"jordan", "8"}, {"castro", "8"}, {"ramirez", "7"},
        {"perez", "7"}, {"james", "7"}, {"dylan", "7"}, {"zack", "7"}, {"luke", "7"}, {"diaz", "7"},
        {"sam", "7"}, {"martin", "7"}, {"carlos", "7"}, {"sanchez", "6"}, {"tommy", "6"},
        {"jason", "6"}, {"zach", "6"}, {"sean", "6"}, {"paul", "6"}, {"john", "6"}, {"eric", "6"},
        {"cody", "6"}, {"brad", "6"}, {"max", "6"}, {"aj", "6"}, {"jonathan", "6"},
        {"stephen", "6"}, {"hernandez", "6"}, {"reyes", "5"}, {"mitch", "5"}, {"jorge", "5"},
        {"danny", "5"}, {"will", "5"}, {"wade", "5"}, {"seth", "5"}, {"cole", "5"},
        {"patrick", "5"}, {"tanner", "5"}, {"steven", "5"}, {"rogers", "5"}, {"hunter", "5"},
        {"rodriguez", "5"}, {"gonzalez", "4"}, {"santana", "4"}, {"thompson", "4"},
        {"charlie", "4"}, {"bradley", "4"}, {"pedro", "4"}, {"lucas", "4"}, {"lopez", "4"},
        {"jones", "4"}, {"jesse", "4"}, {"corey", "4"}, {"brett", "4"}, {"blake", "4"},
        {"chad", "4"}, {"jon", "4"}, {"ian", "4"}, {"de", "4"}, {"christian", "4"}, {"victor", "4"},
        {"tucker", "4"}, {"travis", "4"}, {"robert", "4"}, {"rafael", "4"}, {"williams", "4"},
        {"guerra", "4"}, {"jackson", "4"}, {"crawford", "3"}, {"francisco", "3"}, {"cabrera", "3"},
        {"gregory", "3"}, {"martinez", "3"}, {"white", "3"}, {"urias", "3"}, {"shane", "3"},
        {"rojas", "3"}, {"riley", "3"}, {"ramon", "3"}, {"pablo", "3"}, {"mejia", "3"},
        {"manny", "3"}, {"logan", "3"}, {"lewis", "3"}, {"kelly", "3"}, {"jesus", "3"},
        {"jacob", "3"}, {"hicks", "3"}, {"edwin", "3"}, {"derek", "3"}, {"caleb", "3"},
        {"brian", "3"}, {"brent", "3"}, {"angel", "3"}, {"abreu", "3"}, {"webb", "3"},
        {"tony", "3"}, {"leon", "3"}, {"juan", "3"}, {"joey", "3"}, {"greg", "3"}, {"evan", "3"},
        {"alec", "3"}, {"zac", "3"}, {"tim", "3"}, {"ben", "3"}, {"tj", "3"}, {"jd", "3"},
        {"contreras", "3"}, {"peralta", "3"}, {"walker", "3"}, {"valdez", "3"}, {"thomas", "3"},
        {"suarez", "3"}, {"ronald", "3"}, {"nelson", "3"}, {"miller", "3"}, {"keller", "3"},
        {"alexander", "3"}, {"dustin", "3"}, {"dillon", "3"}, {"corbin", "3"}, {"connor", "3"},
        {"barnes", "3"}, {"andres", "3"}, {"adrian", "3"}, {"spencer", "3"}, {"santiago", "2"},
        {"sandoval", "2"}, {"cristian", "2"}, {"castellanos", "2"}, {"donovan", "2"},
        {"dominic", "2"}, {"domingo", "2"}, {"fletcher", "2"}, {"sheffield", "2"},
        {"fernandez", "2"}, {"severino", "2"}, {"daulton", "2"}, {"richard", "2"},
        {"emmanuel", "2"}, {"holland", "2"}, {"machado", "2"}, {"chapman", "2"}, {"alcantara", "2"},
        {"cameron", "2"}, {"calhoun", "2"}, {"humberto", "2"}, {"peterson", "2"}, {"gurriel", "2"},
        {"mauricio", "2"}, {"griffin", "2"}, {"fernando", "2"}, {"wyatt", "2"}, {"wells", "2"},
        {"trent", "2"}, {"sandy", "2"}, {"rivas", "2"}, {"randy", "2"}, {"ramos", "2"},
        {"raley", "2"}, {"ponce", "2"}, {"peter", "2"}, {"nunez", "2"}, {"moran", "2"},
        {"moore", "2"}, {"mills", "2"}, {"marte", "2"}, {"lance", "2"}, {"julio", "2"},
        {"jimmy", "2"}, {"jared", "2"}, {"isaac", "2"}, {"gavin", "2"}, {"evans", "2"},
        {"elvis", "2"}, {"duffy", "2"}, {"devin", "2"}, {"davis", "2"}, {"craig", "2"},
        {"colin", "2"}, {"chase", "2"}, {"casey", "2"}, {"bruce", "2"}, {"brady", "2"},
        {"bobby", "2"}, {"avila", "2"}, {"andre", "2"}, {"allen", "2"}, {"adams", "2"},
        {"robertson", "2"}, {"gilbert", "2"}, {"yoan", "2"}, {"wood", "2"}, {"wong", "2"},
        {"soto", "2"}, {"ryne", "2"}, {"ross", "2"}, {"pozo", "2"}, {"pete", "2"}, {"nola", "2"},
        {"mark", "2"}, {"lowe", "2"}, {"long", "2"}, {"king", "2"}, {"josé", "2"}, {"jeff", "2"},
        {"javy", "2"}, {"jace", "2"}, {"hyun", "2"}, {"díaz", "2"}, {"hill", "2"}, {"gray", "2"},
        {"gabe", "2"}, {"erik", "2"}, {"dean", "2"}, {"andy", "2"}, {"wil", "2"}, {"may", "2"},
        {"kim", "2"}, {"jay", "2"}, {"fry", "2"}, {"eli", "2"}, {"dan", "2"}, {"chi", "2"},
        {"cal", "2"}, {"yu", "2"}, {"la", "2"}, {"jt", "2"}, {"dj", "2"}, {"lambert", "2"},
        {"polanco", "2"}, {"vladimir", "2"}, {"freeman", "2"}, {"frazier", "2"}, {"perdomo", "2"},
        {"peacock", "2"}, {"zimmer", "2"}, {"wright", "2"}, {"wilmer", "2"}, {"paredes", "2"},
        {"warren", "2"}, {"wander", "2"}, {"antonio", "2"}, {"alvarez", "2"}, {"sergio", "2"},
        {"seager", "2"}, {"santos", "2"}, {"almonte", "2"}, {"alberto", "2"}, {"rondon", "2"},
        {"romine", "2"}, {"romero", "2"}, {"robbie", "2"}, {"oviedo", "2"}, {"ortega", "2"},
        {"stephenson", "2"}, {"oliver", "2"}, {"aguilar", "2"}, {"murphy", "2"}, {"morgan", "2"},
        {"mickey", "2"}, {"megill", "2"}, {"marcus", "2"}, {"manuel", "2"}, {"keegan", "2"},
        {"junior", "2"}, {"julian", "2"}, {"jansen", "2"}, {"hector", "2"}, {"harvey", "2"},
        {"harper", "2"}, {"harold", "2"}, {"german", "2"}, {"fulmer", "2"}, {"franco", "2"},
        {"flores", "2"}, {"farmer", "2"}, {"edward", "2"}, {"devers", "2"}, {"darren", "2"},
        {"cooper", "2"}, {"clarke", "2"}, {"zimmermann", "2"}, {"carson", "2"}, {"barlow", "2"},
        {"bailey", "2"}, {"albert", "2"}, {"johnson", "2"}, {"espinal", "2"}, {"phillips", "2"},
        {"jimenez", "2"}, {"swanson", "2"}, {"stewart", "2"}, {"maldonado", "1"}, {"norwood", "1"},
        {"gregorius", "1"}, {"nogosek", "1"}, {"gonzales", "1"}, {"santillan", "1"},
        {"gonsolin", "1"}, {"santander", "1"}, {"simmons", "1"}, {"alvarado", "1"},
        {"naughton", "1"}, {"sheldon", "1"}, {"odorizzi", "1"}, {"dunning", "1"},
        {"bumgarner", "1"}, {"eshelman", "1"}, {"stallings", "1"}, {"margevicius", "1"},
        {"seabold", "1"}, {"nivaldo", "1"}, {"nittoli", "1"}, {"salvador", "1"}, {"criswell", "1"},
        {"crismatt", "1"}, {"morimando", "1"}, {"crichton", "1"}, {"schrock", "1"},
        {"schmidt", "1"}, {"sanmartin", "1"}, {"lemahieu", "1"}, {"lobstein", "1"},
        {"shoemaker", "1"}, {"plawecki", "1"}, {"saucedo", "1"}, {"sandlin", "1"}, {"sampson", "1"},
        {"betances", "1"}, {"davidson", "1"}, {"mccaughan", "1"}, {"loaisiga", "1"},
        {"newsome", "1"}, {"newcomb", "1"}, {"neidert", "1"}, {"mckenzie", "1"}, {"bernardo", "1"},
        {"allgeyer", "1"}, {"stratton", "1"}, {"bogaerts", "1"}, {"klobosits", "1"},
        {"goldschmidt", "1"}, {"narvaez", "1"}, {"reidfoley", "1"}, {"benjamin", "1"},
        {"chisholm", "1"}, {"chirinos", "1"}, {"diekman", "1"}, {"dickson", "1"}, {"bellatti", "1"},
        {"deshields", "1"}, {"kinerfalefa", "1"}, {"flaherty", "1"}, {"mccarthy", "1"},
        {"mountcastle", "1"}, {"eickhoff", "1"}, {"vogelbach", "1"}, {"hutchison", "1"},
        {"detmers", "1"}, {"donaldson", "1"}, {"stevenson", "1"}, {"kittredge", "1"},
        {"nootbaar", "1"}, {"celestino", "1"}, {"darvish", "1"}, {"darnaud", "1"}, {"mullins", "1"},
        {"thornton", "1"}, {"rougned", "1"}, {"rosscup", "1"}, {"rosario", "1"}, {"newberry", "1"},
        {"rodolfo", "1"}, {"rodgers", "1"}, {"roberto", "1"}, {"velazquez", "1"}, {"winkler", "1"},
        {"willson", "1"}, {"william", "1"}, {"widener", "1"}, {"blackburn", "1"}, {"staumont", "1"},
        {"whitley", "1"}, {"wheeler", "1"}, {"wojciechowski", "1"}, {"trammell", "1"},
        {"seranthony", "1"}, {"huascar", "1"}, {"syndergaard", "1"}, {"moronta", "1"},
        {"morejón", "1"}, {"mondesi", "1"}, {"moncada", "1"}, {"hermosillo", "1"}, {"webster", "1"},
        {"jhonathan", "1"}, {"thielbar", "1"}, {"deichmann", "1"}, {"ridings", "1"},
        {"vierling", "1"}, {"lindblom", "1"}, {"boxberger", "1"}, {"watkins", "1"},
        {"andrelton", "1"}, {"wallach", "1"}, {"giovanny", "1"}, {"devenski", "1"},
        {"gilbreath", "1"}, {"gsellman", "1"}, {"hoskins", "1"}, {"rengifo", "1"}, {"renfroe", "1"},
        {"holaday", "1"}, {"hoffman", "1"}, {"hoerner", "1"}, {"reddick", "1"}, {"mikolas", "1"},
        {"crochet", "1"}, {"álvarez", "1"}, {"gilberto", "1"}, {"palacios", "1"},
        {"kiermaier", "1"}, {"raleigh", "1"}, {"cousins", "1"}, {"cordero", "1"},
        {"misiewicz", "1"}, {"merrill", "1"}, {"mercado", "1"}, {"coonrod", "1"}, {"mendick", "1"},
        {"collins", "1"}, {"coleman", "1"}, {"jankowski", "1"}, {"meadows", "1"},
        {"gonsalves", "1"}, {"clippard", "1"}, {"merryweather", "1"}, {"arozarena", "1"},
        {"mcmahon", "1"}, {"mckenna", "1"}, {"mcguire", "1"}, {"mcgowin", "1"}, {"dominguez", "1"},
        {"clement", "1"}, {"northcraft", "1"}, {"clayton", "1"}, {"claudio", "1"}, {"mazeika", "1"},
        {"demarcus", "1"}, {"musgrove", "1"}, {"mattson", "1"}, {"matthew", "1"}, {"martini", "1"},
        {"marquez", "1"}, {"marchan", "1"}, {"marcell", "1"}, {"marcano", "1"}, {"manning", "1"},
        {"mancini", "1"}, {"toussaint", "1"}, {"madison", "1"}, {"heyward", "1"}, {"herrera", "1"},
        {"heredia", "1"}, {"hentges", "1"}, {"hendrix", "1"}, {"helsley", "1"}, {"heasley", "1"},
        {"cisnero", "1"}, {"haseong", "1"}, {"hartman", "1"}, {"haniger", "1"}, {"hanhold", "1"},
        {"hampson", "1"}, {"jefferies", "1"}, {"quijada", "1"}, {"senzatela", "1"},
        {"jurickson", "1"}, {"bichette", "1"}, {"moustakas", "1"}, {"mckinstry", "1"},
        {"pomeranz", "1"}, {"castano", "1"}, {"carlton", "1"}, {"carlson", "1"}, {"canning", "1"},
        {"baldonado", "1"}, {"brubaker", "1"}, {"grossman", "1"}, {"petricka", "1"},
        {"vincent", "1"}, {"benintendi", "1"}, {"middleton", "1"}, {"gustave", "1"},
        {"brothers", "1"}, {"brosseau", "1"}, {"guilmet", "1"}, {"olivares", "1"}, {"lowther", "1"},
        {"lourdes", "1"}, {"lorenzo", "1"}, {"verdugo", "1"}, {"gallagher", "1"}, {"mathisen", "1"},
        {"grisham", "1"}, {"grichuk", "1"}, {"yusmeiro", "1"}, {"greinke", "1"}, {"greiner", "1"},
        {"grayson", "1"}, {"grandal", "1"}, {"llovera", "1"}, {"giancarlo", "1"}, {"marshall", "1"},
        {"vazquez", "1"}, {"vasquez", "1"}, {"valaika", "1"}, {"buehler", "1"}, {"buchter", "1"},
        {"mcfarland", "1"}, {"schreiber", "1"}, {"goodwin", "1"}, {"goodrum", "1"},
        {"merrifield", "1"}, {"littell", "1"}, {"brusdar", "1"}, {"brogdon", "1"}, {"britton", "1"},
        {"brinson", "1"}, {"breyvic", "1"}, {"brennan", "1"}, {"brendan", "1"}, {"bregman", "1"},
        {"brebbia", "1"}, {"mantiply", "1"}, {"braxton", "1"}, {"brasier", "1"}, {"brandyn", "1"},
        {"turnbull", "1"}, {"dinelson", "1"}, {"harrison", "1"}, {"zuber", "1"}, {"zeuch", "1"},
        {"zerpa", "1"}, {"yusei", "1"}, {"young", "1"}, {"yonny", "1"}, {"yohel", "1"},
        {"yohan", "1"}, {"yency", "1"}, {"yefry", "1"}, {"yandy", "1"}, {"wynns", "1"},
        {"willi", "1"}, {"wieck", "1"}, {"wantz", "1"}, {"walsh", "1"}, {"walls", "1"},
        {"wacha", "1"}, {"gleyber", "1"}, {"votto", "1"}, {"vinny", "1"}, {"vidal", "1"},
        {"vesia", "1"}, {"urena", "1"}, {"upton", "1"}, {"uceta", "1"}, {"tylor", "1"},
        {"trout", "1"}, {"trejo", "1"}, {"touki", "1"}, {"tomas", "1"}, {"pérez", "1"},
        {"terry", "1"}, {"tejay", "1"}, {"tatis", "1"}, {"tarik", "1"}, {"tapia", "1"},
        {"suter", "1"}, {"suero", "1"}, {"strop", "1"}, {"story", "1"}, {"steve", "1"},
        {"souza", "1"}, {"sonny", "1"}, {"solak", "1"}, {"snell", "1"}, {"snead", "1"},
        {"smyly", "1"}, {"short", "1"}, {"shogo", "1"}, {"shawn", "1"}, {"núñez", "1"},
        {"sborz", "1"}, {"sammy", "1"}, {"rowen", "1"}, {"rowan", "1"}, {"rosso", "1"},
        {"roman", "1"}, {"rodon", "1"}, {"robel", "1"}, {"roark", "1"}, {"glasnow", "1"},
        {"reiss", "1"}, {"reese", "1"}, {"quinn", "1"}, {"lópez", "1"}, {"price", "1"},
        {"posey", "1"}, {"petit", "1"}, {"pavin", "1"}, {"parra", "1"}, {"paolo", "1"},
        {"pagan", "1"}, {"packy", "1"}, {"pache", "1"}, {"ozzie", "1"}, {"ozuna", "1"},
        {"osich", "1"}, {"oscar", "1"}, {"olson", "1"}, {"oliva", "1"}, {"okert", "1"},
        {"nomar", "1"}, {"nolin", "1"}, {"nolan", "1"}, {"nimmo", "1"}, {"nicky", "1"},
        {"neuse", "1"}, {"neris", "1"}, {"nance", "1"}, {"nabil", "1"}, {"myers", "1"},
        {"graterol", "1"}, {"munoz", "1"}, {"muncy", "1"}, {"minor", "1"}, {"miley", "1"},
        {"miles", "1"}, {"carpenter", "1"}, {"menez", "1"}, {"mella", "1"}, {"mears", "1"},
        {"means", "1"}, {"mcrae", "1"}, {"mcgee", "1"}, {"mazza", "1"}, {"mayza", "1"},
        {"maton", "1"}, {"mason", "1"}, {"marsh", "1"}, {"marco", "1"}, {"maile", "1"},
        {"mahle", "1"}, {"maeda", "1"}, {"lynch", "1"}, {"lyles", "1"}, {"louis", "1"},
        {"lewin", "1"}, {"leury", "1"}, {"leone", "1"}, {"leody", "1"}, {"lauer", "1"},
        {"lange", "1"}, {"lamet", "1"}, {"kwang", "1"}, {"kowar", "1"}, {"kolby", "1"},
        {"kohei", "1"}, {"knehr", "1"}, {"knapp", "1"}, {"kirby", "1"}, {"keury", "1"},
        {"ketel", "1"}, {"keone", "1"}, {"kenta", "1"}, {"kaleb", "1"}, {"junis", "1"},
        {"judge", "1"}, {"joyce", "1"}, {"jordy", "1"}, {"jonah", "1"}, {"johan", "1"},
        {"jiman", "1"}, {"jerad", "1"}, {"jefry", "1"}, {"jakob", "1"}, {"jaime", "1"},
        {"isiah", "1"}, {"isbel", "1"}, {"irvin", "1"}, {"india", "1"}, {"houck", "1"},
        {"hiura", "1"}, {"henry", "1"}, {"heath", "1"}, {"hearn", "1"}, {"hayes", "1"},
        {"hatch", "1"}, {"hardy", "1"}, {"hader", "1"}, {"haase", "1"}, {"green", "1"},
        {"grant", "1"}, {"godoy", "1"}, {"glenn", "1"}, {"garza", "1"}, {"fried", "1"},
        {"frias", "1"}, {"foley", "1"}, {"floro", "1"}, {"fiers", "1"}, {"felix", "1"},
        {"fedde", "1"}, {"faria", "1"}, {"ervin", "1"}, {"ernie", "1"}, {"erick", "1"},
        {"enoli", "1"}, {"engel", "1"}, {"ender", "1"}, {"ellis", "1"}, {"elias", "1"},
        {"ehire", "1"}, {"eflin", "1"}, {"edman", "1"}, {"edgar", "1"}, {"duran", "1"},
        {"dubon", "1"}, {"duane", "1"}, {"drury", "1"}, {"doval", "1"}, {"dolis", "1"},
        {"deivi", "1"}, {"dauri", "1"}, {"darin", "1"}, {"damon", "1"}, {"cueto", "1"},
        {"crowe", "1"}, {"crick", "1"}, {"clint", "1"}, {"clase", "1"}, {"chang", "1"},
        {"cesar", "1"}, {"cease", "1"}, {"cavan", "1"}, {"canha", "1"}, {"byron", "1"},
        {"burns", "1"}, {"burch", "1"}, {"bundy", "1"}, {"bubic", "1"}, {"bryce", "1"},
        {"brown", "1"}, {"brody", "1"}, {"brock", "1"}, {"brice", "1"}, {"brach", "1"},
        {"billy", "1"}, {"betts", "1"}, {"berti", "1"}, {"beede", "1"}, {"beaty", "1"},
        {"bauer", "1"}, {"baker", "1"}, {"bader", "1"}, {"asher", "1"}, {"ashby", "1"},
        {"arauz", "1"}, {"alexy", "1"}, {"akeem", "1"}, {"ahmed", "1"}, {"adell", "1"},
        {"acuna", "1"}, {"inciarte", "1"}, {"bukauskas", "1"}, {"spitzbarth", "1"},
        {"bostick", "1"}, {"borucki", "1"}, {"bolanos", "1"}, {"kaprielian", "1"}, {"gittens", "1"},
        {"castillo", "1"}, {"giolito", "1"}, {"gimenez", "1"}, {"yastrzemski", "1"},
        {"carrasco", "1"}, {"yuli", "1"}, {"ynoa", "1"}, {"yang", "1"}, {"wily", "1"},
        {"wick", "1"}, {"whit", "1"}, {"ward", "1"}, {"voth", "1"}, {"voit", "1"}, {"vest", "1"},
        {"trey", "1"}, {"tres", "1"}, {"topa", "1"}, {"todd", "1"}, {"tate", "1"}, {"sosa", "1"},
        {"siri", "1"}, {"sims", "1"}, {"shed", "1"}, {"shea", "1"}, {"shaw", "1"}, {"seby", "1"},
        {"sano", "1"}, {"sale", "1"}, {"ruiz", "1"}, {"rony", "1"}, {"romy", "1"}, {"romo", "1"},
        {"roel", "1"}, {"rios", "1"}, {"rhys", "1"}, {"reid", "1"}, {"reed", "1"}, {"pina", "1"},
        {"phil", "1"}, {"pham", "1"}, {"pena", "1"}, {"owen", "1"}, {"otto", "1"}, {"omar", "1"},
        {"odor", "1"}, {"oday", "1"}, {"ober", "1"}, {"noah", "1"}, {"niko", "1"}, {"nido", "1"},
        {"nico", "1"}, {"nate", "1"}, {"moll", "1"}, {"mize", "1"}, {"matz", "1"}, {"lynn", "1"},
        {"lugo", "1"}, {"loup", "1"}, {"ljay", "1"}, {"liam", "1"}, {"latz", "1"}, {"lars", "1"},
        {"lail", "1"}, {"kurt", "1"}, {"kuhl", "1"}, {"krol", "1"}, {"kris", "1"}, {"kole", "1"},
        {"kohl", "1"}, {"kodi", "1"}, {"kirk", "1"}, {"kent", "1"}, {"kemp", "1"}, {"kela", "1"},
        {"kean", "1"}, {"junk", "1"}, {"jong", "1"}, {"jojo", "1"}, {"joan", "1"}, {"jhon", "1"},
        {"jean", "1"}, {"jazz", "1"}, {"jack", "1"}, {"ivey", "1"}, {"isan", "1"}, {"hoyt", "1"},
        {"holt", "1"}, {"hoby", "1"}, {"heim", "1"}, {"head", "1"}, {"hays", "1"}, {"happ", "1"},
        {"hans", "1"}, {"hale", "1"}, {"hahn", "1"}, {"gose", "1"}, {"gary", "1"}, {"ford", "1"},
        {"enns", "1"}, {"eloy", "1"}, {"eddy", "1"}, {"dunn", "1"}, {"dohy", "1"}, {"difo", "1"},
        {"didi", "1"}, {"daza", "1"}, {"dane", "1"}, {"dahl", "1"}, {"curt", "1"}, {"cruz", "1"},
        {"cron", "1"}, {"cory", "1"}, {"cobb", "1"}, {"clay", "1"}, {"choi", "1"}, {"chaz", "1"},
        {"chas", "1"}, {"cave", "1"}, {"cain", "1"}, {"bush", "1"}, {"burr", "1"}, {"buck", "1"},
        {"boyd", "1"}, {"bote", "1"}, {"bohm", "1"}, {"belt", "1"}, {"bell", "1"}, {"bass", "1"},
        {"bard", "1"}, {"baez", "1"}, {"amir", "1"}, {"amed", "1"}, {"alek", "1"}, {"alan", "1"},
        {"akin", "1"}, {"akil", "1"}, {"adon", "1"}, {"abad", "1"}, {"wes", "1"}, {"tom", "1"},
        {"ryu", "1"}, {"ruf", "1"}, {"roe", "1"}, {"rob", "1"}, {"rex", "1"}, {"rea", "1"},
        {"ray", "1"}, {"puk", "1"}, {"pop", "1"}, {"pat", "1"}, {"ort", "1"}, {"mac", "1"},
        {"lux", "1"}, {"lou", "1"}, {"lee", "1"}, {"law", "1"}, {"kay", "1"}, {"jin", "1"},
        {"jed", "1"}, {"jax", "1"}, {"gio", "1"}, {"gil", "1"}, {"dom", "1"}, {"del", "1"},
        {"daz", "1"}, {"cam", "1"}, {"baz", "1"}, {"art", "1"}, {"ty", "1"}, {"rj", "1"},
        {"jp", "1"}, {"jo", "1"}, {"jc", "1"}, {"jb", "1"}, {"cj", "1"}, {"bo", "1"}, {"a", "1"},
        {"caratini", "1"}, {"hamilton", "1"}, {"campusano", "1"}, {"brantley", "1"},
        {"blewett", "1"}, {"larnach", "1"}, {"lamonte", "1"}, {"woodruff", "1"}, {"woodford", "1"},
        {"lagares", "1"}, {"gerardo", "1"}, {"geraldo", "1"}, {"castellani", "1"},
        {"rortvedt", "1"}, {"genesis", "1"}, {"sittinger", "1"}, {"dietrich", "1"},
        {"biagini", "1"}, {"hyeonjong", "1"}, {"campbell", "1"}, {"lavarnway", "1"},
        {"madrigal", "1"}, {"camarena", "1"}, {"urshela", "1"}, {"urquidy", "1"}, {"reynolds", "1"},
        {"reynaldo", "1"}, {"stripling", "1"}, {"gausman", "1"}, {"garneau", "1"}, {"garlick", "1"},
        {"gardner", "1"}, {"haggerty", "1"}, {"moreland", "1"}, {"bemboom", "1"}, {"beasley", "1"},
        {"piscotty", "1"}, {"tucupita", "1"}, {"aristides", "1"}, {"preston", "1"},
        {"pressly", "1"}, {"bazardo", "1"}, {"baumann", "1"}, {"bassitt", "1"}, {"barrero", "1"},
        {"barrera", "1"}, {"barreda", "1"}, {"baragar", "1"}, {"cronenworth", "1"},
        {"fairbanks", "1"}, {"coulombe", "1"}, {"pollock", "1"}, {"strasburg", "1"},
        {"kranick", "1"}, {"yamamoto", "1"}, {"wainwright", "1"}, {"smeltzer", "1"},
        {"mercedes", "1"}, {"holloway", "1"}, {"fuentes", "1"}, {"refsnyder", "1"},
        {"kintzler", "1"}, {"kolarek", "1"}, {"koerner", "1"}, {"robinson", "1"}, {"pivetta", "1"},
        {"knizner", "1"}, {"conforto", "1"}, {"phillip", "1"}, {"freddie", "1"}, {"franmil", "1"},
        {"frankie", "1"}, {"franchy", "1"}, {"framber", "1"}, {"kirilloff", "1"},
        {"cleavinger", "1"}, {"avisail", "1"}, {"sherriff", "1"}, {"gutiérrez", "1"},
        {"finnegan", "1"}, {"melancon", "1"}, {"peguero", "1"}, {"zunino", "1"}, {"pearson", "1"},
        {"schebler", "1"}, {"zavala", "1"}, {"zamora", "1"}, {"kikuchi", "1"}, {"kieboom", "1"},
        {"kickham", "1"}, {"yordan", "1"}, {"weathers", "1"}, {"yermin", "1"}, {"yennsy", "1"},
        {"yelich", "1"}, {"aroldis", "1"}, {"yajure", "1"}, {"yadier", "1"}, {"yadiel", "1"},
        {"arihara", "1"}, {"hendriks", "1"}, {"arenado", "1"}, {"xander", "1"}, {"sceroler", "1"},
        {"fleming", "1"}, {"wisdom", "1"}, {"winker", "1"}, {"willie", "1"}, {"paulino", "1"},
        {"wendle", "1"}, {"welker", "1"}, {"weigel", "1"}, {"weaver", "1"}, {"walton", "1"},
        {"paddack", "1"}, {"vosler", "1"}, {"vimael", "1"}, {"villar", "1"}, {"keuchel", "1"},
        {"kershaw", "1"}, {"vaughn", "1"}, {"varsho", "1"}, {"valera", "1"}, {"adrianza", "1"},
        {"kelenic", "1"}, {"culberson", "1"}, {"ottavino", "1"}, {"kebryan", "1"},
        {"bellinger", "1"}, {"tyrone", "1"}, {"realmuto", "1"}, {"andujar", "1"}, {"turner", "1"},
        {"trayce", "1"}, {"torres", "1"}, {"tomlin", "1"}, {"tinoco", "1"}, {"thorpe", "1"},
        {"thairo", "1"}, {"heineman", "1"}, {"tayler", "1"}, {"suzuki", "1"}, {"sulser", "1"},
        {"torreyes", "1"}, {"stubbs", "1"}, {"strahm", "1"}, {"stevie", "1"}, {"stella", "1"},
        {"stefan", "1"}, {"steele", "1"}, {"stassi", "1"}, {"stanek", "1"}, {"speier", "1"},
        {"solano", "1"}, {"sogard", "1"}, {"yonathan", "1"}, {"snyder", "1"}, {"alzolay", "1"},
        {"slater", "1"}, {"skubal", "1"}, {"singer", "1"}, {"sierra", "1"}, {"shreve", "1"},
        {"shohei", "1"}, {"sheets", "1"}, {"sewald", "1"}, {"senzel", "1"}, {"semien", "1"},
        {"segura", "1"}, {"scrubb", "1"}, {"schoop", "1"}, {"sadler", "1"}, {"alfonso", "1"},
        {"aledmys", "1"}, {"alcides", "1"}, {"rucker", "1"}, {"rooker", "1"}, {"romano", "1"},
        {"robles", "1"}, {"roansy", "1"}, {"desclafani", "1"}, {"wittgren", "1"}, {"rivero", "1"},
        {"rivera", "1"}, {"richie", "1"}, {"reymin", "1"}, {"rendon", "1"}, {"renato", "1"},
        {"reiver", "1"}, {"raynel", "1"}, {"ranger", "1"}, {"randal", "1"}, {"raisel", "1"},
        {"rainey", "1"}, {"raimel", "1"}, {"akiyama", "1"}, {"feltner", "1"}, {"profar", "1"},
        {"poteet", "1"}, {"plutko", "1"}, {"plesac", "1"}, {"pineda", "1"}, {"pinder", "1"},
        {"pillar", "1"}, {"pierce", "1"}, {"phelps", "1"}, {"peters", "1"}, {"peraza", "1"},
        {"paxton", "1"}, {"patton", "1"}, {"patino", "1"}, {"parker", "1"}, {"owings", "1"},
        {"oswalt", "1"}, {"oneill", "1"}, {"ohtani", "1"}, {"ohearn", "1"}, {"ogrady", "1"},
        {"odubel", "1"}, {"obrien", "1"}, {"underwood", "1"}, {"newman", "1"}, {"nestor", "1"},
        {"naylor", "1"}, {"nathan", "1"}, {"naquin", "1"}, {"blandino", "1"}, {"nathaniel", "1"},
        {"trivino", "1"}, {"triston", "1"}, {"muller", "1"}, {"trevino", "1"}, {"treinen", "1"},
        {"blackmon", "1"}, {"morton", "1"}, {"moreta", "1"}, {"mookie", "1"}, {"montas", "1"},
        {"moniak", "1"}, {"molina", "1"}, {"minter", "1"}, {"minaya", "1"}, {"milone", "1"},
        {"milner", "1"}, {"meyers", "1"}, {"mercer", "1"}, {"medina", "1"}, {"farrell", "1"},
        {"mcneil", "1"}, {"mchugh", "1"}, {"mccann", "1"}, {"mazara", "1"}, {"mayers", "1"},
        {"maybin", "1"}, {"matzek", "1"}, {"margot", "1"}, {"marcos", "1"}, {"maples", "1"},
        {"manoah", "1"}, {"manaea", "1"}, {"maikel", "1"}, {"madero", "1"}, {"machin", "1"},
        {"familia", "1"}, {"luetge", "1"}, {"lowrie", "1"}, {"lindor", "1"}, {"lakins", "1"},
        {"kutter", "1"}, {"kremer", "1"}, {"marmolejos", "1"}, {"kopech", "1"}, {"konner", "1"},
        {"kolten", "1"}, {"knight", "1"}, {"knebel", "1"}, {"kluber", "1"}, {"kinley", "1"},
        {"keynan", "1"}, {"keston", "1"}, {"kervin", "1"}, {"kepler", "1"}, {"kenley", "1"},
        {"torrens", "1"}, {"kazmir", "1"}, {"justus", "1"}, {"jovani", "1"}, {"joshua", "1"},
        {"johnny", "1"}, {"jharel", "1"}, {"jewell", "1"}, {"jeurys", "1"}, {"jeremy", "1"},
        {"jeimer", "1"}, {"willians", "1"}, {"javier", "1"}, {"jarren", "1"}, {"jarred", "1"},
        {"jarlin", "1"}, {"janson", "1"}, {"jannis", "1"}, {"jandel", "1"}, {"jahmai", "1"},
        {"jacoby", "1"}, {"jackie", "1"}, {"acevedo", "1"}, {"quantrill", "1"}, {"ibáñez", "1"},
        {"abraham", "1"}, {"mitchell", "1"}, {"hudson", "1"}, {"howard", "1"}, {"houser", "1"},
        {"hosmer", "1"}, {"dickerson", "1"}, {"hernan", "1"}, {"hedges", "1"}, {"harris", "1"},
        {"hanser", "1"}, {"hammer", "1"}, {"guzman", "1"}, {"guduan", "1"}, {"gordon", "1"},
        {"gomber", "1"}, {"godley", "1"}, {"ginkel", "1"}, {"gibaut", "1"}, {"gerrit", "1"},
        {"george", "1"}, {"garver", "1"}, {"garcía", "1"}, {"gallen", "1"}, {"honeywell", "1"},
        {"friedl", "1"}, {"freddy", "1"}, {"france", "1"}, {"fraley", "1"}, {"fowler", "1"},
        {"foster", "1"}, {"fortes", "1"}, {"flexen", "1"}, {"falter", "1"}, {"espino", "1"},
        {"erasmo", "1"}, {"emilio", "1"}, {"eduard", "1"}, {"dusten", "1"}, {"dugger", "1"},
        {"duggar", "1"}, {"duffey", "1"}, {"dozier", "1"}, {"dobnak", "1"}, {"diplan", "1"},
        {"deolis", "1"}, {"dellin", "1"}, {"delino", "1"}, {"dejong", "1"}, {"degrom", "1"},
        {"dayton", "1"}, {"davies", "1"}, {"darien", "1"}, {"dansby", "1"}, {"dallas", "1"},
        {"dalbec", "1"}, {"dakota", "1"}, {"steckenrider", "1"}, {"lawrence", "1"}, {"curtis", "1"},
        {"crouse", "1"}, {"cotton", "1"}, {"cortes", "1"}, {"correa", "1"}, {"conner", "1"},
        {"conley", "1"}, {"colton", "1"}, {"colten", "1"}, {"colome", "1"}, {"collin", "1"},
        {"civale", "1"}, {"cishek", "1"}, {"vanmeter", "1"}, {"cionel", "1"}, {"higashioka", "1"},
        {"chavez", "1"}, {"chasen", "1"}, {"chacin", "1"}, {"lucchesi", "1"}, {"hirokazu", "1"},
        {"cedric", "1"}, {"casali", "1"}, {"carter", "1"}, {"camilo", "1"}, {"cahill", "1"},
        {"buxton", "1"}, {"butera", "1"}, {"buster", "1"}, {"burnes", "1"}, {"burger", "1"},
        {"bummer", "1"}, {"brujan", "1"}, {"bruihl", "1"}, {"brooks", "1"}, {"brewer", "1"},
        {"brentz", "1"}, {"brault", "1"}, {"bowden", "1"}, {"bleier", "1"}, {"blaine", "1"},
        {"biggio", "1"}, {"bielak", "1"}, {"bieber", "1"}, {"biddle", "1"}, {"bergen", "1"},
        {"bender", "1"}, {"bednar", "1"}, {"yarbrough", "1"}, {"yasmani", "1"}, {"yardley", "1"},
        {"barria", "1"}, {"baddoo", "1"}, {"laureano", "1"}, {"eugenio", "1"}, {"axford", "1"},
        {"avilan", "1"}, {"arroyo", "1"}, {"arraez", "1"}, {"archie", "1"}, {"archer", "1"},
        {"aramis", "1"}, {"aquino", "1"}, {"antone", "1"}, {"andrus", "1"}, {"altuve", "1"},
        {"alonso", "1"}, {"almora", "1"}, {"allard", "1"}, {"alford", "1"}, {"alfaro", "1"},
        {"guerrero", "1"}, {"alcala", "1"}, {"albies", "1"}, {"albers", "1"}, {"alaniz", "1"},
        {"guenther", "1"}, {"adrián", "1"}, {"adonis", "1"}, {"adolis", "1"}, {"adbert", "1"},
        {"abbott", "1"}, {"teoscar", "1"}, {"teheran", "1"}, {"cristopher", "1"}, {"estrada", "1"},
        {"estevez", "1"}, {"escobar", "1"}, {"darwinzon", "1"}, {"candelario", "1"},
        {"altavilla", "1"}, {"taveras", "1"}, {"freeland", "1"}, {"hilliard", "1"},
        {"tarpley", "1"}, {"taillon", "1"}, {"taijuan", "1"}, {"hendricks", "1"}, {"richards", "1"},
        {"eovaldi", "1"}, {"iglesias", "1"}, {"enrique", "1"}, {"foltynewicz", "1"},
        {"duplantier", "1"}, {"jhoulys", "1"}, {"emanuel", "1"}, {"montgomery", "1"},
        {"frankoff", "1"}, {"astudillo", "1"}, {"elledge", "1"}, {"elieser", "1"},
        {"karinchak", "1"}, {"alejandro", "1"}, {"meisinger", "1"}, {"jeffrey", "1"},
        {"jeffers", "1"}, {"barnhart", "1"}, {"springer", "1"}, {"gallegos", "1"},
        {"wilkerson", "1"}, {"jameson", "1"}, {"effross", "1"}, {"barraclough", "1"},
        {"guillorme", "1"}, {"guillermo", "1"}, {"lovelady", "1"}, {"mccutchen", "1"},
        {"eduardo", "1"}, {"mccullers", "1"}, {"stroman", "1"}, {"strider", "1"}, {"edmundo", "1"},
        {"hildenberger", "1"}, {"stiever", "1"}, {"funkhouser", "1"}, {"stephan", "1"},
        {"stashak", "1"}, {"starlin", "1"}, {"stanton", "1"}, {"stammen", "1"}, {"hernández", "1"},
        {"szapucki", "1"}, {"lorenzen", "1"}, {"adalberto", "1"}, {"zimmerman", "1"},
        {"springs", "1"}, {"spenser", "1"}, {"magneuris", "1"}, {"quackenbush", "1"},
        {"solomon", "1"}, {"gosselin", "1"}, {"mccormick", "1"}, {"sawamura", "1"},
        {"longoria", "1"}, {"sebastian", "1"}, {"mcclanahan", "1"}, {"bettinger", "1"},
        {"slegers", "1"}, {"whitlock", "1"}};

    for (File file : new File[] {ngramsCsv, ngramsXlsx}) {
      try (TabularWorksheetReader rows = SpreadsheetFactory.getInstance()
          .readActiveTabularWorksheet(() -> new FileInputStream(file))) {
        assertThat(rows.stream().map(row -> {
          return new String[] {
              row.findCellByColumnName("ngram").map(c -> c.getValue(String.class)).get(),
              row.findCellByColumnName("count").map(c -> c.getValue(Integer.class)).get()
                  .toString()};
        }).toArray(String[][]::new), is(expected));
      }
    }
  }
}
